# Generated by Django 4.2 on 2023-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='article',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
