# Generated by Django 4.2 on 2023-06-03 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_remove_article_downvotes_remove_article_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
