# Generated by Django 4.2 on 2023-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_article_downvoted_user_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
